In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "nPJf5FFhl6DXPpC4NQSxAL5REFwR0nb0" #C'est le clé api de materials project personnel?
mp_id = "mp-23040"

In [3]:
with MPRester(mp_key) as m:
    struct = m.get_structure_by_material_id(mp_id)
analyse = SpacegroupAnalyzer(struct)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Structure analysis

In [4]:
print(struct) #Données sur la structure

Full Formula (Ca2 P1 I1)
Reduced Formula: Ca2PI
abc   :   7.828366   7.828366   7.828367
angles:  31.966665  31.966669  31.966669
pbc   :       True       True       True
Sites (4)
  #  SP           a          b         c    magmom
---  ----  --------  ---------  --------  --------
  0  Ca    0.770118   0.770118  0.770118        -0
  1  Ca    0.229882   0.229882  0.229882        -0
  2  P     0.5        0.5       0.5              0
  3  I     0         -0         0                0


#### Vecteurs de base résau direct

In [5]:
print("vecteurs de base du résau direct:")
lattice = struct.lattice #Simplifer code
print("(a,b,c) = ","\n","(",lattice.matrix[0],",","\n",lattice.matrix[1],",","\n",lattice.matrix[2],")","\n")

vecteurs de base du résau direct:
(a,b,c) =  
 ( [4.14681860e+00 1.63696000e-03 6.63982006e+00] , 
 [1.90431365 3.68370679 6.63982006] , 
 [2.68702000e-03 1.63697000e-03 7.82836615e+00] ) 



#### Norme des vecteurs résau direct 

In [6]:
print("norme des vecteurs de base du résau direct (en [Å]):")
print("(a,b,c) = ","\n","(",lattice.a,",","\n",lattice.b,",","\n",lattice.c,")","\n")

norme des vecteurs de base du résau direct (en [Å]):
(a,b,c) =  
 ( 7.828366215892203 , 
 7.828366152745209 , 
 7.828366782299683 ) 



#### Vecteurs de base résau réciproque

In [7]:
print("vecteurs de base du résau réciproque:")
rlattice = struct.lattice.reciprocal_lattice #Simplifer code
print("(a,b,c) = ","\n","(",rlattice.matrix[0],",","\n",rlattice.matrix[1],",","\n",rlattice.matrix[2],")","\n")

vecteurs de base du résau réciproque:
(a,b,c) =  
 ( [ 1.51606225e+00 -7.83094386e-01 -3.56624551e-04] , 
 [-1.02320780e-04  1.70636521e+00 -3.56778626e-04] , 
 [-1.28579846 -0.78309471  0.8032228 ] ) 



#### Norme des vecteurs résau réciproque

In [8]:
print("norme des vecteurs de base du résau direct (en [Å]):")
print("(a,b,c) = ","\n","(",rlattice.a,",","\n",rlattice.b,",","\n",rlattice.c,")","\n")

norme des vecteurs de base du résau direct (en [Å]):
(a,b,c) =  
 ( 1.706365049332668 , 
 1.7063652486341085 , 
 1.706365103743214 ) 



#### Structure

In [9]:
type = analyse.get_lattice_type()
g_ponctuel = analyse.get_space_group_symbol()
systeme = analyse.get_crystal_system()

print("Le type du maille du système cristallin est:","\n",type,g_ponctuel[0],"\n")
print("Groupe ponctuel: ", g_ponctuel,"\n")
print("Système cristallin: ", systeme,"\n")
#systéme: orthorombique, groupe ponctuel: R-3m

Le type du maille du système cristallin est: 
 rhombohedral R 

Groupe ponctuel:  R-3m 

Système cristallin:  trigonal 

